### ISSUE TITLE
Proposal: gray out or hide/disable Hunts that user has already visited

### ISSUE THREAD

**Issue by lambtron** [denoland/saaskit#286]
what do you think? that way user who is logged in can filter on Hunts that they haven't seen yet

**Comment by iuioiua** [comment]
I like this idea. The simplest way to signify whether the user has visited a link is to use the [`:visited` CSS pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited). I.e. let the browser change the colour of the link once it's been visited. WDYT?

**Comment by niklasmtj** [comment]
I like the idea of using the `:visited` pseudo-class. Since one might want to revisit a recent hunt I would not hide or disable those but rather just signal the user that she/he already visited the respective hunt. 

When using the pseudo-class, do you think using the same color in a different tone? So since we use `text-gray-500` for our regular links I would suggest using `text-gray-300` or even `text-gray-200`. What do you think?

**Comment by iuioiua** [comment]
I'm open to whichever colour/shade as long as it conveys to the user clearly that the link has been visited. Google uses purple to do that.
