### ISSUE TITLE
discussion: blog

### ISSUE THREAD

**Issue by lino-levan** [denoland/saaskit#6]
I know a blog feed is on the roadmap (https://github.com/orgs/denoland/projects/35?pane=issue&itemId=22944835), but I was wondering what the internal project specifications are.

Would they be in markdown? Would it integrate with popular CMS offerings?

This also opens up some bigger discussions surrounding who saaskit is for. If we decide to go with markdown, can a non-technical content manager write a blog post?

Curious to hear your thoughts @iuioiua and @lambtron!

**Comment by iuioiua** [comment]
The exact specifications for future features are yet to be solidified. Even though SaaSKit is oriented to those building a SaaS website, it can be applied to anyone wanting to use Fresh and Deno to build any website by picking and choosing features that apply to them.

Markdown is an excellent language for the blog because, as you mention, it's easy to learn, even for non-technical authors.

**Comment by iuioiua** [comment]
Related discussion with @niklasmtj: https://discord.com/channels/684898665143206084/1085986084653109438/1087325490026651658

**Comment by iuioiua** [comment]
Blog functionality has been added in #18.
